In [269]:
import pandas as pd
import numpy as np
import datetime as dt

In [270]:
df=pd.read_excel('SampleSept23.xlsx')
df=pd.DataFrame(df)
df.head()

,PNRNO,Region,State,City,TicketNo,Order No,Seat No.,Customer GST Number,PassengerName,PassengerMobile,Gender,EmailID,Age,IDProofType,IDProofNumber,JFromCityName,JToCityName,PickupAreaName,PM_PickupName,PickupLandMark,PM_Address,PickupDatetime,DropAreaName,DropName,DropLandMark,DropAddress,DropDateTime,RMRouteName,RFromCityName,RToCityName,RouteName,RouteCode,JourneyDate,BookingDate,Booking Type,Booked By Branch,Booked Agent,Book User,BaseAmount,SeatAmount,BaseFare,AgentCommission,BranchCommission,12% IGST,6% CGST,6% SGST,RoundUP,Discount,Bookingstatus,CancelDate,CancelAmount,RefundCharge1,Refund Prev. Booked GST,Refund Charge IGST,Refund Charge CGST,Refund Charge SGST,RefundAmount,Cancel Remark,Difference Amount,Reshedule Charge,Reshedule GST,TDRCharge,WalletRefundCharges,SurCharges,InsuranceCharges,MagicBoxCharges,GoldSeatCharges,CouponCode,BusType,Amenity,GST Amenity,Total Payable Amount,My Cash Used Amt,Net Payable Amt,Franchise/Agent Wallet Used Amt.,Net Banking / Credit Card,Payment / Wallet Transaction ID,Net Banking/ Credit Card/ Wallet/ Agent/ Franchise - Reference,Agent Commission TDS,Branch Commission TDS,Partial Cancellation ID - Mapping with old PNR,Agent Markup,B2B / NON B2B,Old Mobile No.,Alternate Name,Cabin Host Name,Depot
0,2141268,(blank),Andhra Pradesh,Vijayawada,691 434,(blank),#1B,(blank),Ambati Ravindranath,9515963532,M,ravindranatha@gmail.com,45,(blank),(blank),Vijayawada,Hyderabad,(blank),"RTC Bus Stand, Vijayawada",Opp kalikamatha Temple,Near RTC Bus Stand,2023-09-03 22:30:00,(blank),Jeedimetla,Opp Indian Oil Pump,Near Jeedimetla Bus Depot,2023-09-04 05:15:00,Vijayawada To Hyderabad,Vijayawada,Hyderabad,Vijayawada To Hyderabad,30023 BZA-HYD 2230,2023-09-03,2023-09-02 10:14:00,Agent,API Branch,API_Redbus_GreenCell_Express,API User,738,738,738,73.8,0.0,0.0,0.0,0.0,0,0.0,Booked,(blank),0,0.0,0.0,0.0,0.0,0.0,0,(blank),0.0,0,0.0,0.0,0.0,0.0,0,0,0,(blank),A/C,0,0,738,0.0,738,0,0,1 041 402,NaN,0.0,0.0,0,0,NON B2B,NaN,NaN,NaN,Hyderabad Depot
1,2141271,(blank),Madhya Pradesh,Bhopal,691 437,(blank),#2C,(blank),Deepali Sharma,7828372301,F,sharmassh001@gmail.com,33,(blank),(blank),Bhopal,Indore,(blank),ISBT Bhopal (Verma Travels),Near ISBT Habibganj,"Shop 01, Commercial Complex",2023-09-03 12:00:00,(blank),Sarwate Bus Stand,Ticket counter no 1,E-Bus Platform 1,2023-09-03 16:30:00,Bhopal To Indore,Bhopal,Indore,Bhopal To Indore,10064 BHO-IDR 1230,2023-09-03,2023-09-02 10:15:00,Agent,API Branch,API_Paytm_GreenCell_Express,API User,414,414,414,41.4,0.0,0.0,0.0,0.0,0,0.0,Booked,(blank),0,0.0,0.0,0.0,0.0,0.0,0,(blank),0.0,0,0.0,0.0,0.0,0.0,0,0,0,(blank),A/C,0,0,414,0.0,414,0,0,1 041 404,NaN,0.0,0.0,0,0,NON B2B,NaN,NaN,NaN,Bhopal Depo
2,2141276,(blank),Telangana,Hyderabad,691 442,(blank),#3D,(blank),Gopi kishore,9441761568,M,gopikishore2006@gmail.com,36,(blank),(blank),Hyderabad,Vijayawada,(blank),SR Nagar,Pillar No 1026,SR Nagar Metro Station,2023-09-03 12:15:00,(blank),"RTC Bus Stand, Vijayawada",Opp kalikamatha Temple,Near RTC Bus Stand,2023-09-03 18:50:00,Hyderabad To Vijayawada,Hyderabad,Vijayawada,Hyderabad To Vijayawada,30002 HYD-BZA 1200,2023-09-03,2023-09-02 10:16:00,Agent,API Branch,API_Redbus_GreenCell_Express,API User,532,532,532,53.2,0.0,0.0,0.0,0.0,0,0.0,Booked,(blank),0,0.0,0.0,0.0,0.0,0.0,0,(blank),0.0,0,0.0,0.0,0.0,0.0,0,0,0,(blank),A/C,0,0,532,0.0,532,0,0,1 041 409,NaN,0.0,0.0,0,0,NON B2B,NaN,NaN,NaN,Hyderabad Depot
3,2142376,(blank),Telangana,Hyderabad,692 541,(blank),#3C,(blank),D R Kumar VATTIPROLU,8500066123,M,prabhutejkumar@gmail.com,58,(blank),(blank),Hyderabad,Vijayawada,(blank),Uppal Metro Station,Near Master Chef Restaurant,Uppal Metro Station,2023-09-02 23:40:00,(blank),"RTC Bus Stand, Vijayawada",Opp kalikamatha Temple,Near RTC Bus Stand,2023-09-03 05:25:00,Hyderabad To Vijayawada,Hyderabad,Vijayawada,Hyderabad To Vijayawada,30031 HYD-BZA 2230,2023-09-02,2023-09-02 12:29:00,Agent,API Branch,API_Redbus_GreenCell_Express,API User,499,499,499,49.9,0.0,0.0,0.0,0.0,0,0.0,Booked,(blank),0,0.0,0.0,0.0,0.0,0.0,0,(blank),0.0,0,0.0,0.0,0.0,0.0,0,0,0,(blank),A/C,0,0,499,0.0,499,0,0,1 042 451,NaN,0.0,0.0,0,0,NON B2B,NaN,NaN,NaN,Hyderabad Depot
4,2142388,(blank),Madhya Pradesh,Bhopal,692 553,(blank),#1A,(blank),komal bijore,9691090965,F,salonibijore@gmail.com,45,(blank),(blank),Bhopal,Indore,(blank),ISBT Bhopal (Verma Travels),Near ISBT Habibganj,"Shop 01, Commercial Complex",2023-09-03 16:50:00,(blank),Radisson Square (C21 Biz Park),Near C21 Business Park,Near C21 Business Park,2023-09-03 20:50:00,Bhopal To Indore,Bhopal,Indore,Bhopal To Indore,10079 BHO-IDR 1730,2023-09-03,2023-09-02 12:29:00,Agent,API Branch,API_Redbus_GreenCell_Express,API User,414,414,414,41.4,0.0,0.0,0.0,0.0,0,0.0,Booked,(blank),0,0.0,0.0,0.0,0.0,0.0,0,(blank),0.0,0,0.0,0.0,0.0,0.0,0,0,0,(blank),A/C,0,0,414,0.0,414,0,0,1 042 461,NaN,0.0,0.0,2 141 332,0,NON B2B,NaN,NaN,NaN,Bhopal Depo

In [271]:
df1= df[df["Bookingstatus"]=='Booked']
df1

,PNRNO,Region,State,City,TicketNo,Order No,Seat No.,Customer GST Number,PassengerName,PassengerMobile,Gender,EmailID,Age,IDProofType,IDProofNumber,JFromCityName,JToCityName,PickupAreaName,PM_PickupName,PickupLandMark,PM_Address,PickupDatetime,DropAreaName,DropName,DropLandMark,DropAddress,DropDateTime,RMRouteName,RFromCityName,RToCityName,RouteName,RouteCode,JourneyDate,BookingDate,Booking Type,Booked By Branch,Booked Agent,Book User,BaseAmount,SeatAmount,BaseFare,AgentCommission,BranchCommission,12% IGST,6% CGST,6% SGST,RoundUP,Discount,Bookingstatus,CancelDate,CancelAmount,RefundCharge1,Refund Prev. Booked GST,Refund Charge IGST,Refund Charge CGST,Refund Charge SGST,RefundAmount,Cancel Remark,Difference Amount,Reshedule Charge,Reshedule GST,TDRCharge,WalletRefundCharges,SurCharges,InsuranceCharges,MagicBoxCharges,GoldSeatCharges,CouponCode,BusType,Amenity,GST Amenity,Total Payable Amount,My Cash Used Amt,Net Payable Amt,Franchise/Agent Wallet Used Amt.,Net Banking / Credit Card,Payment / Wallet Transaction ID,Net Banking/ Credit Card/ Wallet/ Agent/ Franchise - Reference,Agent Commission TDS,Branch Commission TDS,Partial Cancellation ID - Mapping with old PNR,Agent Markup,B2B / NON B2B,Old Mobile No.,Alternate Name,Cabin Host Name,Depot
0,2141268,(blank),Andhra Pradesh,Vijayawada,691 434,(blank),#1B,(blank),Ambati Ravindranath,9515963532,M,ravindranatha@gmail.com,45,(blank),(blank),Vijayawada,Hyderabad,(blank),"RTC Bus Stand, Vijayawada",Opp kalikamatha Temple,Near RTC Bus Stand,2023-09-03 22:30:00,(blank),Jeedimetla,Opp Indian Oil Pump,Near Jeedimetla Bus Depot,2023-09-04 05:15:00,Vijayawada To Hyderabad,Vijayawada,Hyderabad,Vijayawada To Hyderabad,30023 BZA-HYD 2230,2023-09-03,2023-09-02 10:14:00,Agent,API Branch,API_Redbus_GreenCell_Express,API User,738,738,738,73.80,0.0,0.0,0.0,0.0,0,0.0,Booked,(blank),0,0.0,0.0,0.0,0.0,0.0,0,(blank),0.0,0,0.0,0.0,0.0,0.0,0,0,0,(blank),A/C,0,0,738,0.0,738,0,0,1 041 402,NaN,0.00,0.0,0,0,NON B2B,NaN,NaN,NaN,Hyderabad Depot
1,2141271,(blank),Madhya Pradesh,Bhopal,691 437,(blank),#2C,(blank),Deepali Sharma,7828372301,F,sharmassh001@gmail.com,33,(blank),(blank),Bhopal,Indore,(blank),ISBT Bhopal (Verma Travels),Near ISBT Habibganj,"Shop 01, Commercial Complex",2023-09-03 12:00:00,(blank),Sarwate Bus Stand,Ticket counter no 1,E-Bus Platform 1,2023-09-03 16:30:00,Bhopal To Indore,Bhopal,Indore,Bhopal To Indore,10064 BHO-IDR 1230,2023-09-03,2023-09-02 10:15:00,Agent,API Branch,API_Paytm_GreenCell_Express,API User,414,414,414,41.40,0.0,0.0,0.0,0.0,0,0.0,Booked,(blank),0,0.0,0.0,0.0,0.0,0.0,0,(blank),0.0,0,0.0,0.0,0.0,0.0,0,0,0,(blank),A/C,0,0,414,0.0,414,0,0,1 041 404,NaN,0.00,0.0,0,0,NON B2B,NaN,NaN,NaN,Bhopal Depo
2,2141276,(blank),Telangana,Hyderabad,691 442,(blank),#3D,(blank),Gopi kishore,9441761568,M,gopikishore2006@gmail.com,36,(blank),(blank),Hyderabad,Vijayawada,(blank),SR Nagar,Pillar No 1026,SR Nagar Metro Station,2023-09-03 12:15:00,(blank),"RTC Bus Stand, Vijayawada",Opp kalikamatha Temple,Near RTC Bus Stand,2023-09-03 18:50:00,Hyderabad To Vijayawada,Hyderabad,Vijayawada,Hyderabad To Vijayawada,30002 HYD-BZA 1200,2023-09-03,2023-09-02 10:16:00,Agent,API Branch,API_Redbus_GreenCell_Express,API User,532,532,532,53.20,0.0,0.0,0.0,0.0,0,0.0,Booked,(blank),0,0.0,0.0,0.0,0.0,0.0,0,(blank),0.0,0,0.0,0.0,0.0,0.0,0,0,0,(blank),A/C,0,0,532,0.0,532,0,0,1 041 409,NaN,0.00,0.0,0,0,NON B2B,NaN,NaN,NaN,Hyderabad Depot
3,2142376,(blank),Telangana,Hyderabad,692 541,(blank),#3C,(blank),D R Kumar VATTIPROLU,8500066123,M,prabhutejkumar@gmail.com,58,(blank),(blank),Hyderabad,Vijayawada,(blank),Uppal Metro Station,Near Master Chef Restaurant,Uppal Metro Station,2023-09-02 23:40:00,(blank),"RTC Bus Stand, Vijayawada",Opp kalikamatha Temple,Near RTC Bus Stand,2023-09-03 05:25:00,Hyderabad To Vijayawada,Hyderabad,Vijayawada,Hyderabad To Vijayawada,30031 HYD-BZA 2230,2023-09-02,2023-09-02 12:29:00,Agent,API Branch,API_Redbus_GreenCell_Express,API User,499,499,499,49.90,0.0,0.0,0.0,0.0,0,0.0,Booked,(blank),0,0.0,0.0,0.0,0.0,0.0,0,(blank),0.0,0,0.0,0.0,0.0,0.0,0,0,0,(blank),A/C,0,0,499,0.0,499,0,0,1 042 451,NaN,0.00,0.0,0,0,NON B2B,NaN,NaN,NaN,Hyderabad Depot
4,2142388,(blank),Madhya Pradesh,Bhopal,692 553,(blank),#1A,(blank),komal bijore,9691090965,F,salonibijore@gmail.com,45,(blank),(blank),Bhopal,Indore,(blank),ISBT Bhopal (Verma Travels),Near ISBT Habibganj,"Shop 01, Commercial Complex",2023-09-03 16:50:00,(blank),Radisson Square (C21 Biz Park),Near C21 Business Park,Near C21 Business Park,2023-09-03 20:50:00,Bhopal To Indore,Bhopal,Indore,Bhopal To Indore,10079 BHO-IDR 1730,2023-09-03,2023-09-02 12:29:00,Agent,API Branch,API_Redbus_GreenCell_Express,API User,414,414,414,41.40,0.0,0.0,0.0,0.0,0,0.0,Booked,(blank),0,0.0,0.0,0.0,0.0,0.0,0,(blank),0.0,0,0.0,0.0,0.0,0.0,0,0,0,(blank),A/C,0,0,414,0.0,414,0,0,1 042 461,NaN,0.00,0.0,2 141 332,0,NON B2B,NaN,NaN,NaN,Bhopal Depo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41834,2165789,(blank),Delhi,Delhi,715 939,NaN,#7D,(blank),RIHAN,8882926113,F,(blank),34,(blank),(blank),Delhi,Chandigarh,(blank),ISBT Kashmiri Gate (PF 1&2),"E-Bus Platform no 1 & 2,","E-Bus Platform no 1 & 2, Maharana Pratap ISBT,...",2023-09-05 14:30:00,(blank),ISBT Sec-43 (HP Petrol Pump),Opp ISBT Sector 43,Opp ISBT Sector 43 Near HPCL Pump,2023-09-05 19:55:00,Delhi To Chandigarh,Delhi,Chandigarh,Delhi To Chandigarh,20025 DEL - CHD 1430,2023-09-05,2023-09-05 14:06:00,Agent,Agent Branch,Blue World,Agent User,464,487,435,65.25,0.0,0.0,26.1,26.1,0,29.0,Booked,(blank),0,0.0,0.0,0.0,0.0,0.0,0,(blank),0.0,0,0.0,0.0,0.0,0.0,0,0,0,(blank),A/C,0,0,487.2,0.0,487.2,425.21,0,1 064 832,Booking Agent,3.26,0.0,0,0,NON B2B,NaN,NaN,NaN,GHAZIABAD DEPOT
41835,2165790,(blank),Andhra Pradesh,Kanchikacherla,715 940,(blank),#5A,(blank),Gokul,6300747461,M,gokuldhnalakshmi@gmial.com,20,(blank),(blank),Kanchikacherla,Hyderabad,(blank),Kanchikacherla Bypass,(blank),Kanchikacherla Underpass,2023-09-05 23:20:00,(blank),Suraram X Roads,Near RTC Bus Stop,"Medak Road, Suraram X Roads",2023-09-06 05:20:00,Vijayawada To Hyderabad,Vijayawada,Hyderabad,Vijayawada To Hyderabad,30023 BZA-HYD 2230,2023-09-05,2023-09-05 14:06:00,Agent,API Branch,API_Redbus_GreenCell_Express,API User,678,678,678,67.80,0.0,0.0,0.0,0.0,0,0.0,Booked,(blank),0,0.0,0.0,0.0,0.0,0.0,0,(blank),0.0,0,0.0,0.0,0.0,0.0,0,0,0,(blank),A/C,0,0,678,0.0,678,0,0,1 064 833,NaN,0.00,0.0,0,0,NON B2B,NaN,NaN,NaN,Hyderabad Depot
41836,2216397,(blank),Rajasthan,Jaipur,766 517,(blank),#4C,(blank),Sejal,7351073646,F,joshi.gagan24@gmail.com,25,(blank),(blank),Jaipur,Delhi,(blank),Jaipur Railway station circle,Opposite ICICI ATM,Jaipur Railway station circle,2023-09-14 11:30:00,(blank),Dhaula Kuan (HPCL Pump),Near RR Hospital,"Metro Pillar 102, Near Footover Bridge",2023-09-14 17:25:00,Jaipur To Delhi,Jaipur,Delhi,Jaipur To Delhi,40017 JPR - DEL 1130,2023-09-14,2023-09-13 20:54:00,Agent,API Branch,API_Redbus_GreenCell_Express,API User,379,379,379,37.90,0.0,0.0,0.0,0.0,0,0.0,Booked,(blank),0,0.0,0.0,0.0,0.0,0.0,0,(blank),0.0,0,0.0,0.0,0.0,0.0,0,0,0,(blank),A/C,0,0,379,0.0,379,0,0,1 113 399,NaN,0.00,0.0,0,0,NON B2B,NaN,NaN,NaN,GHAZIABAD DEPOT
41837,2216397,(blank),Rajasthan,Jaipur,766 517,(blank),#4D,(blank),Gagan joshi,7351073646,M,joshi.gagan24@gmail.com,23,(blank),(blank),Jaipur,Delhi,(blank),Jaipur Railway station circle,Opposite ICICI ATM,Jaipur Railway station circle,2023-09-14 11:30:00,(blank),Dhaula Kuan (HPCL Pump),Near RR Hospital,"Metro Pillar 102, Near Footover Bridge",2023-09-14 17:25:00,Jaipur To Delhi,Jaipur,Delhi,Jaipur To Delhi,40017 JPR - DEL 1130,2023-09-14,2023-09-13 20:54:00,Agent,API Branch,API_Redbus_GreenCell_Express,API User,379,379,379,37.90,0.0,0.0,0.0,0.0,0,0.0,Booked,(blank),0,0.0,0.0,0.0,0.0,0.0,0,(blank),0.0,0,0.0,0.0,0.0,0.0,0,0,0,(blank),A/C,0,0,379,0.0,379,0,0,1 113 399,NaN,0.00,0.0,0,0,NON B2B,NaN,NaN,NaN,GHAZIABAD DEPOT
41838,2216401,(blank),Delhi,Delhi,766 521,(blank),#6D,(blank),Akriti,7989317528,F,bhcmarketing@botanichealthcare.net,25,(blank),(blank),Delhi,Haridwar,(blank),"NueGo Lounge, Kashmiri Gate",Besides Aadhar Seva Kendra,"Metro Station Gate no 1, Opp. Edelco Food Court",2023-09-14 06:00:00,(blank),"Kashyap Ashram, Haridwar",Near Gulab Sweets,"Opp. Rishikul Bridge, Devpura, NH 58 Delhi Deh...",2023-09-14 11:30:00,Delhi To Dehradun,Delhi,Dehradun,Delhi To Dehradun,50001 DEL - DDN 0600,2023-09-14,2023-09-13 20:54:00,Agent,API Branch,API_Redbus_GreenCell_Express,API User,477,477,477,47.70,0.0,0.0,0.0,0.0,0,0.0,Booked,(blank),0,0.0,0.0,0.0,0.0,0.0,0,(blank),0.0,0,0.0,0.0,0.0,0.0,0,0,0,(blank),A/C,0,0,477,0.0,477,0,0,1 113 403,NaN,0.00,0.0,0,0,NON B2B,NaN,NaN,NaN,GHAZIABAD DEPOT

In [272]:
df1.dtypes

PNRNO               int64
Region             object
State              object
City               object
TicketNo           object
                    ...
B2B / NON B2B      object
Old Mobile No.     object
Alternate Name     object
Cabin Host Name    object
Depot              object
Length: 87, dtype: object

In [273]:
df2= pd.read_excel('Agent_Commission_Master.xlsx')
df2=pd.DataFrame(df2)
df2.head()

c:\Users\Sahil\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

,PartnerID,PartnerName,PartnerCode,PartnerType,SAPCode,SAPCustomerCode,CompanyName,EffectiveDate,StateName,CityName,Address,OfficeMobileNo,Region,StatusName,Partner,Infinity,Tertiary Comm,Cross Tertiary Comm
0,Pending Approval,TAJ Express,NaN,NaN,NaN,NaN,NaN,2023-05-31,Uttar Pradesh,Noida,Sec -37 NOIDA,9.540017e+09,North,Pending,Retail @10%,NaN,0.1,0.1
1,Pending Approval,Murali Krishna,NaN,NaN,NaN,NaN,NaN,2023-05-31,Karnataka,Bengaluru,General Stall No - Bmtc Building N R Colony Ba...,9.448492e+09,South,Pending,Retail @10%,NaN,0.1,0.1
2,Pending Approval,Sathwik Money Transfer,NaN,NaN,NaN,NaN,NaN,2023-05-31,Andhra Pradesh,Guntur,"Peddakakani road,Opp canara bank ,Guntur",9.989897e+09,South,Pending,Retail @10%,NaN,0.1,0.1
3,Pending Approval,MVR Public Relations,NaN,NaN,NaN,NaN,NaN,2023-05-31,Andhra Pradesh,Vijayawada,"Fiber road,Krishna lanka,Vijayawada,AP",9.154443e+09,South,Pending,Retail @10%,NaN,0.1,0.1
4,Pending Approval,Sravya travels,NaN,NaN,NaN,NaN,NaN,2023-05-31,Andhra Pradesh,Vijayawada,"Opp Masajid Street,Eluru road,Vijayawada,AP",9.246483e+09,South,Pending,Retail @10%,NaN,0.1,0.1

In [274]:
# Fetched mobile no only from agent master dataframe
df3=df2["OfficeMobileNo"]

In [275]:
pd.set_option('display.max_columns',500)
df1.head()

,PNRNO,Region,State,City,TicketNo,Order No,Seat No.,Customer GST Number,PassengerName,PassengerMobile,Gender,EmailID,Age,IDProofType,IDProofNumber,JFromCityName,JToCityName,PickupAreaName,PM_PickupName,PickupLandMark,PM_Address,PickupDatetime,DropAreaName,DropName,DropLandMark,DropAddress,DropDateTime,RMRouteName,RFromCityName,RToCityName,RouteName,RouteCode,JourneyDate,BookingDate,Booking Type,Booked By Branch,Booked Agent,Book User,BaseAmount,SeatAmount,BaseFare,AgentCommission,BranchCommission,12% IGST,6% CGST,6% SGST,RoundUP,Discount,Bookingstatus,CancelDate,CancelAmount,RefundCharge1,Refund Prev. Booked GST,Refund Charge IGST,Refund Charge CGST,Refund Charge SGST,RefundAmount,Cancel Remark,Difference Amount,Reshedule Charge,Reshedule GST,TDRCharge,WalletRefundCharges,SurCharges,InsuranceCharges,MagicBoxCharges,GoldSeatCharges,CouponCode,BusType,Amenity,GST Amenity,Total Payable Amount,My Cash Used Amt,Net Payable Amt,Franchise/Agent Wallet Used Amt.,Net Banking / Credit Card,Payment / Wallet Transaction ID,Net Banking/ Credit Card/ Wallet/ Agent/ Franchise - Reference,Agent Commission TDS,Branch Commission TDS,Partial Cancellation ID - Mapping with old PNR,Agent Markup,B2B / NON B2B,Old Mobile No.,Alternate Name,Cabin Host Name,Depot
0,2141268,(blank),Andhra Pradesh,Vijayawada,691 434,(blank),#1B,(blank),Ambati Ravindranath,9515963532,M,ravindranatha@gmail.com,45,(blank),(blank),Vijayawada,Hyderabad,(blank),"RTC Bus Stand, Vijayawada",Opp kalikamatha Temple,Near RTC Bus Stand,2023-09-03 22:30:00,(blank),Jeedimetla,Opp Indian Oil Pump,Near Jeedimetla Bus Depot,2023-09-04 05:15:00,Vijayawada To Hyderabad,Vijayawada,Hyderabad,Vijayawada To Hyderabad,30023 BZA-HYD 2230,2023-09-03,2023-09-02 10:14:00,Agent,API Branch,API_Redbus_GreenCell_Express,API User,738,738,738,73.8,0.0,0.0,0.0,0.0,0,0.0,Booked,(blank),0,0.0,0.0,0.0,0.0,0.0,0,(blank),0.0,0,0.0,0.0,0.0,0.0,0,0,0,(blank),A/C,0,0,738,0.0,738,0,0,1 041 402,NaN,0.0,0.0,0,0,NON B2B,NaN,NaN,NaN,Hyderabad Depot
1,2141271,(blank),Madhya Pradesh,Bhopal,691 437,(blank),#2C,(blank),Deepali Sharma,7828372301,F,sharmassh001@gmail.com,33,(blank),(blank),Bhopal,Indore,(blank),ISBT Bhopal (Verma Travels),Near ISBT Habibganj,"Shop 01, Commercial Complex",2023-09-03 12:00:00,(blank),Sarwate Bus Stand,Ticket counter no 1,E-Bus Platform 1,2023-09-03 16:30:00,Bhopal To Indore,Bhopal,Indore,Bhopal To Indore,10064 BHO-IDR 1230,2023-09-03,2023-09-02 10:15:00,Agent,API Branch,API_Paytm_GreenCell_Express,API User,414,414,414,41.4,0.0,0.0,0.0,0.0,0,0.0,Booked,(blank),0,0.0,0.0,0.0,0.0,0.0,0,(blank),0.0,0,0.0,0.0,0.0,0.0,0,0,0,(blank),A/C,0,0,414,0.0,414,0,0,1 041 404,NaN,0.0,0.0,0,0,NON B2B,NaN,NaN,NaN,Bhopal Depo
2,2141276,(blank),Telangana,Hyderabad,691 442,(blank),#3D,(blank),Gopi kishore,9441761568,M,gopikishore2006@gmail.com,36,(blank),(blank),Hyderabad,Vijayawada,(blank),SR Nagar,Pillar No 1026,SR Nagar Metro Station,2023-09-03 12:15:00,(blank),"RTC Bus Stand, Vijayawada",Opp kalikamatha Temple,Near RTC Bus Stand,2023-09-03 18:50:00,Hyderabad To Vijayawada,Hyderabad,Vijayawada,Hyderabad To Vijayawada,30002 HYD-BZA 1200,2023-09-03,2023-09-02 10:16:00,Agent,API Branch,API_Redbus_GreenCell_Express,API User,532,532,532,53.2,0.0,0.0,0.0,0.0,0,0.0,Booked,(blank),0,0.0,0.0,0.0,0.0,0.0,0,(blank),0.0,0,0.0,0.0,0.0,0.0,0,0,0,(blank),A/C,0,0,532,0.0,532,0,0,1 041 409,NaN,0.0,0.0,0,0,NON B2B,NaN,NaN,NaN,Hyderabad Depot
3,2142376,(blank),Telangana,Hyderabad,692 541,(blank),#3C,(blank),D R Kumar VATTIPROLU,8500066123,M,prabhutejkumar@gmail.com,58,(blank),(blank),Hyderabad,Vijayawada,(blank),Uppal Metro Station,Near Master Chef Restaurant,Uppal Metro Station,2023-09-02 23:40:00,(blank),"RTC Bus Stand, Vijayawada",Opp kalikamatha Temple,Near RTC Bus Stand,2023-09-03 05:25:00,Hyderabad To Vijayawada,Hyderabad,Vijayawada,Hyderabad To Vijayawada,30031 HYD-BZA 2230,2023-09-02,2023-09-02 12:29:00,Agent,API Branch,API_Redbus_GreenCell_Express,API User,499,499,499,49.9,0.0,0.0,0.0,0.0,0,0.0,Booked,(blank),0,0.0,0.0,0.0,0.0,0.0,0,(blank),0.0,0,0.0,0.0,0.0,0.0,0,0,0,(blank),A/C,0,0,499,0.0,499,0,0,1 042 451,NaN,0.0,0.0,0,0,NON B2B,NaN,NaN,NaN,Hyderabad Depot
4,2142388,(blank),Madhya Pradesh,Bhopal,692 553,(blank),#1A,(blank),komal bijore,9691090965,F,salonibijore@gmail.com,45,(blank),(blank),Bhopal,Indore,(blank),ISBT Bhopal (Verma Travels),Near ISBT Habibganj,"Shop 01, Commercial Complex",2023-09-03 16:50:00,(blank),Radisson Square (C21 Biz Park),Near C21 Business Park,Near C21 Business Park,2023-09-03 20:50:00,Bhopal To Indore,Bhopal,Indore,Bhopal To Indore,10079 BHO-IDR 1730,2023-09-03,2023-09-02 12:29:00,Agent,API Branch,API_Redbus_GreenCell_Express,API User,414,414,414,41.4,0.0,0.0,0.0,0.0,0,0.0,Booked,(blank),0,0.0,0.0,0.0,0.0,0.0,0,(blank),0.0,0,0.0,0.0,0.0,0.0,0,0,0,(blank),A/C,0,0,414,0.0,414,0,0,1 042 461,NaN,0.0,0.0,2 141 332,0,NON B2B,NaN,NaN,NaN,Bhopal Depo

In [276]:
df1['SeatAmount']= df6['SeatAmount'].astype(str).str.replace(' ','')

C:\Users\Sahil\AppData\Local\Temp\ipykernel_20564\120358379.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['SeatAmount']= df6['SeatAmount'].astype(str).str.replace(' ','')

In [277]:
#
df4=df1[['Seat No.','SeatAmount','AgentCommission','BranchCommission']]
df4
# df4['total'] = df1['AgentCommission'].sum()

      Seat No. SeatAmount  AgentCommission  BranchCommission
0          #1B      738.0            73.80               0.0
1          #2C      414.0            41.40               0.0
2          #3D      532.0            53.20               0.0
3          #3C      499.0            49.90               0.0
4          #1A      414.0            41.40               0.0
...        ...        ...              ...               ...
41834      #7D      487.0            65.25               0.0
41835      #5A      678.0            67.80               0.0
41836      #4C      379.0            37.90               0.0
41837      #4D      379.0            37.90               0.0
41838      #6D      477.0            47.70               0.0

[36062 rows x 4 columns]

In [278]:
df4['merge']=df4['AgentCommission']+ df4['BranchCommission']
# df5=df4.drop(columns='full_name',axis=1)
df6=df4.drop(columns='merge',axis=1)
# df6
df4

# df6['Merge'] = df4['Merge'].replace([0], df4['Seat No.']*100/(112))
# df6

C:\Users\Sahil\AppData\Local\Temp\ipykernel_20564\1108025172.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4['merge']=df4['AgentCommission']+ df4['BranchCommission']

      Seat No. SeatAmount  AgentCommission  BranchCommission  merge
0          #1B      738.0            73.80               0.0  73.80
1          #2C      414.0            41.40               0.0  41.40
2          #3D      532.0            53.20               0.0  53.20
3          #3C      499.0            49.90               0.0  49.90
4          #1A      414.0            41.40               0.0  41.40
...        ...        ...              ...               ...    ...
41834      #7D      487.0            65.25               0.0  65.25
41835      #5A      678.0            67.80               0.0  67.80
41836      #4C      379.0            37.90               0.0  37.90
41837      #4D      379.0            37.90               0.0  37.90
41838      #6D      477.0            47.70               0.0  47.70

[36062 rows x 5 columns]

In [279]:
df4['SeatAmount']= df4['SeatAmount'].astype(str).str.replace(' ','')

C:\Users\Sahil\AppData\Local\Temp\ipykernel_20564\1020066105.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4['SeatAmount']= df4['SeatAmount'].astype(str).str.replace(' ','')

In [280]:
df4.dtypes

Seat No.             object
SeatAmount           object
AgentCommission     float64
BranchCommission    float64
merge               float64
dtype: object

In [281]:
df4['SeatAmount']=df4['SeatAmount'].astype(float)
df4.dtypes

C:\Users\Sahil\AppData\Local\Temp\ipykernel_20564\1007094731.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4['SeatAmount']=df4['SeatAmount'].astype(float)

Seat No.             object
SeatAmount          float64
AgentCommission     float64
BranchCommission    float64
merge               float64
dtype: object

In [282]:
# reduce=12/100
df10=df4['SeatAmount']*0.12
df10

0        88.56
1        49.68
2        63.84
3        59.88
4        49.68
         ...
41834    58.44
41835    81.36
41836    45.48
41837    45.48
41838    57.24
Name: SeatAmount, Length: 36062, dtype: float64

In [292]:
df6['Merge'] = df4['merge'].replace([0],[df10])
df6

      Seat No. SeatAmount  AgentCommission  BranchCommission  Merge
0          #1B      738.0            73.80               0.0  73.80
1          #2C      414.0            41.40               0.0  41.40
2          #3D      532.0            53.20               0.0  53.20
3          #3C      499.0            49.90               0.0  49.90
4          #1A      414.0            41.40               0.0  41.40
...        ...        ...              ...               ...    ...
41834      #7D      487.0            65.25               0.0  65.25
41835      #5A      678.0            67.80               0.0  67.80
41836      #4C      379.0            37.90               0.0  37.90
41837      #4D      379.0            37.90               0.0  37.90
41838      #6D      477.0            47.70               0.0  47.70

[36062 rows x 5 columns]

In [294]:
df6.to_csv('Final_output.csv')

In [283]:
df4

      Seat No.  SeatAmount  AgentCommission  BranchCommission  merge
0          #1B       738.0            73.80               0.0  73.80
1          #2C       414.0            41.40               0.0  41.40
2          #3D       532.0            53.20               0.0  53.20
3          #3C       499.0            49.90               0.0  49.90
4          #1A       414.0            41.40               0.0  41.40
...        ...         ...              ...               ...    ...
41834      #7D       487.0            65.25               0.0  65.25
41835      #5A       678.0            67.80               0.0  67.80
41836      #4C       379.0            37.90               0.0  37.90
41837      #4D       379.0            37.90               0.0  37.90
41838      #6D       477.0            47.70               0.0  47.70

[36062 rows x 5 columns]

In [284]:
df4['SeatAmount'].value_counts()

SeatAmount
414.0     4520
400.0     3847
380.0     1282
435.0     1162
499.0     1123
          ...
901.0        1
1263.0       1
1020.0       1
870.0        1
872.0        1
Name: count, Length: 753, dtype: int64

In [285]:
df6.to_csv('loop.csv')

PermissionError: [Errno 13] Permission denied: 'loop.csv'

In [ ]:
# df15=df1[df1['Booked Agent']=='API_Redbus_GreenCell_Express']
# df15=df15[['Seat No.','BaseFare','AgentCommission']]
# df15

In [ ]:
df15=df1.drop_duplicates('Booked Agent')
df15.shape

(104, 87)

In [ ]:
d= []
for col in df15.iterrows():
    dff=col['Booked Agent'], col['AgentCommission'],col['Seat No.']
    d.append(dff)
df28 = pd.DataFrame(d)
df29 = df28.rename({0: 'Booked Agent', 1: 'AgentCommission', 2: 'Seat No.'}, axis=1)

In [ ]:
df29

                        Booked Agent  AgentCommission Seat No.
0       API_Redbus_GreenCell_Express            73.80      #1B
1        API_Paytm_GreenCell_Express            41.40      #2C
2      API_Abhibus_GreenCell_Express            88.50      #6A
3    B2C_Deepsense_GreenCell Express             0.00      #6A
4    API_Maventech_GreenCell_Express            52.80      #2A
..                               ...              ...      ...
99                 Sri Durga Agencys            53.20      #5D
100             Gagan travels Indore            35.70      #7C
101                   Mahakal Travel            65.25      #1B
102                        CityPondy            25.20      #5C
103     New Gendar Tour  and Travels            35.70      #1D

[104 rows x 3 columns]

In [ ]:
# df29.to_excel('loop_output.xlsx')

In [ ]:
df8=['API_Redbus_GreenCell_Express','API_Paytm_GreenCell_Express','API_Maventech_GreenCell_Express',"API_Via.Com_GreenCell_Express",'API_Abhibus_GreenCell_Express','Api_Easemytrip_GCE','B2C_Deepsense_GreenCell Express']
df9 = df1.loc[df1['Booked Agent'].isin(df8)]
df10 = df1[df1['Booked Agent'].isin(df8)]
df11=df10.pivot(columns='Booked Agent',values='Seat No.')
df11

Booked Agent,API_Abhibus_GreenCell_Express,API_Maventech_GreenCell_Express,API_Paytm_GreenCell_Express,API_Redbus_GreenCell_Express,API_Via.Com_GreenCell_Express,Api_Easemytrip_GCE,B2C_Deepsense_GreenCell Express
0,NaN,NaN,NaN,#1B,NaN,NaN,NaN
1,NaN,NaN,#2C,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,#3D,NaN,NaN,NaN
3,NaN,NaN,NaN,#3C,NaN,NaN,NaN
4,NaN,NaN,NaN,#1A,NaN,NaN,NaN
...,...,...,...,...,...,...,...
41828,#8D,NaN,NaN,NaN,NaN,NaN,NaN
41835,NaN,NaN,NaN,#5A,NaN,NaN,NaN
41836,NaN,NaN,NaN,#4C,NaN,NaN,NaN
41837,NaN,NaN,NaN,#4D,NaN,NaN,NaN
41838,NaN,NaN,NaN,#6D,NaN,NaN,NaN

In [ ]:
df11 = df11.replace(np.NaN, '')
df11.reset_index=True
df11

Booked Agent,API_Abhibus_GreenCell_Express,API_Maventech_GreenCell_Express,API_Paytm_GreenCell_Express,API_Redbus_GreenCell_Express,API_Via.Com_GreenCell_Express,Api_Easemytrip_GCE,B2C_Deepsense_GreenCell Express
0,,,,#1B,,,
1,,,#2C,,,,
2,,,,#3D,,,
3,,,,#3C,,,
4,,,,#1A,,,
...,...,...,...,...,...,...,...
41828,#8D,,,,,,
41835,,,,#5A,,,
41836,,,,#4C,,,
41837,,,,#4D,,,
41838,,,,#6D,,,

In [ ]:
# df11.to_csv(r'D:\\vs code\\OTA_output.csv')